name: CI/CD Pipeline
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

# Login to DockerHUb

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

  #Build and push Docker Image

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{secrets.DOCKER_USERNAME}}/deploydemo
          IMAGE_TAG=latest
          SHA_TAG=${{ github.sha }}
          
          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          
          echo "Tagging Docker image with SHA..."
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$SHA_TAG
          
          echo "Pushing images..."
          
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:$SHA_TAG
          
          
          
          
          
          
